name: Train‑and‑Evaluate

on:
  workflow_dispatch:
    inputs:
      test_size:
        description: 'Data % to test'
        required: true
        default: '0.2'
      random_state:
        description: 'Random seed'
        required: true
        default: '42'
      c:
        description: 'C parameter in LogisticRegression'
        required: true
        default: '1.0'

jobs:
  checkout_and_download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download dataset
        run: |
          mkdir -p data
          wget -q https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv \
               -O data/diabetes.csv

      - name: Upload dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-data
          path: data/diabetes.csv

  train:
    runs-on: ubuntu-latest
    needs: checkout_and_download
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: diabetes-data
          path: data

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py \
            --data_dir=data \
            --test_size=${{ github.event.inputs.test_size }} \
            --random_state=${{ github.event.inputs.random_state }} \
            --c=${{ github.event.inputs.c }}

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pkl

  evaluate:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: diabetes-data
          path: data
      - uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: .

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Evaluate model
        run: |
          python evaluate.py \
            --data_dir=data \
            --random_state=${{ github.event.inputs.random_state }}

      - name: Upload evaluation report
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-report
          path: evaluation.txt
